### ISSUE TITLE
Footer underlines intersect icons.

### ISSUE THREAD

**Issue by pilleye** [QuantumStack/Descartes-client#17]
In the footer of the homepage, the underlines on hover intersect with the icons. As a potential fix, either the underline could be moved down, or the underline could start at the text instead of at the icon.

<img width="87" alt="Capture" src="https://user-images.githubusercontent.com/29032680/59390477-fcc48a00-8d36-11e9-8481-5cfce7ce9dcc.PNG">

**Comment by fishdev** [comment]
I was planning to remove the icons in favor of a slightly cleaner footer anyway, which will resolve this issue.
